project:
  title: "Programming for Data Science"
  type: book
  output-dir: docs

book:
  title: "Programming for Data Science"
  author: "Rafael C. Alvarado"
  date: "05/08/2021"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
    - part: "Getting Started"  
      chapters:  
        - lessons/M01_GettingStarted/Untitled.ipynb
    - part: "Appendices"
      chapters:
        - references.qmd

format:
  html:
    toc: true

bibliography:
  - refs.bib




