project:
  title: "DS 5100: Programming for Data Science"
  type: book
  output-dir: docs

# website:
  
book:
  title: "DS 5001: Programming for Data Science"
  author: "Rafael C. Alvarado"
  date: "05/08/2021"
  page-navigation: true
  navbar: 
    search: true
    pinned: true
    collapse: true
  site-url: https://ontoligent.github.io/DS5100-2023-07-R
  repo-url: https://github.com/ontoligent/DS5100-2023-07-R
  chapters:
    - part: index.qmd 
      chapters:
      - modules/m00/syllabus.qmd
      - topics/oreilly-accounts.qmd
    - part: modules/m01/m01-intro.qmd
      chapters:
      - topics/rivanna.qmd
      - topics/unix.qmd
      - topics/setting-up-ssh.qmd
      - topics/git-and-github.qmd
      - modules/m01/m01-using-rivanna.qmd
      - modules/m01/m01-activity-github.qmd
    - part: modules/m02/m02-intro.qmd
      chapters:
      - topics/on-data.qmd
      - topics/python-object-types.qmd
      - modules/m02/m02-activity-hello-world.qmd
      - modules/m02/m02-activity-jupyter-lab-on-rivanna.qmd
      - notebooks/M02_BasicPython/M02-01-DataTypes.ipynb
      - notebooks/M02_BasicPython/M02-02-Numbers.ipynb
      - notebooks/M02_BasicPython/M02-03-Booleans.ipynb
      - notebooks/M02_BasicPython/M02-04-Strings.ipynb
      - notebooks/M02_BasicPython/M02-05-Structures.ipynb
    - part: modules/m03/m03-intro.qmd
      chapters:
      - notebooks/M03_ControlStructures/M03-01-ControlStructures.ipynb
      - notebooks/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
      - notebooks/M03_ControlStructures/M03-03-Comprehensions.ipynb
    - part: modules/m04/m04-intro.qmd
      chapters: 
      - notebooks/M04_PythonFunctions/M04-01-Importing.ipynb
      - notebooks/M04_PythonFunctions/M04-02-Functions.ipynb
      - notebooks/M04_PythonFunctions/M04-03-LambdaFunctions.ipynb
      - notebooks/M04_PythonFunctions/M04-04-RecursiveFunctions.ipynb
      - notebooks/M04_PythonFunctions/M04-05-Scope.ipynb
      - notebooks/M04_PythonFunctions/M04-06-FunctionsCallingFunctions.ipynb
    # - part: "05 NumPy"
    # - part: "06 Pandas"
    # - part: "07 Classes"
    # - part: "08 Testing"
    # - part: "09 Modules"
    # - part: "10 Basic R"
    # - part: "11 Dplyr"
    # - part: "12 Visualization"
    # - part: "13 Agile"
  sidebar:
    # style: docked
    style: floating
    background: light
    collapse-level: 1
    
format:
  html:
    toc: true
    theme: cosmo
    number-sections: false
    # number-depth: 1

  # pdf:
  #   documentclass: scrreport    

bibliography:
  - refs.bib




