project:
  title: "Programming for Data Science"
  type: book
  output-dir: docs

book:
  title: "Programming for Data Science"
  author: "Rafael C. Alvarado"
  date: "05/08/2021"
  chapters:
    - part: "Frontmatter"
      chapters:
      - index.qmd
    - part: "M01 Getting Started"  
      chapters:  
        - lessons/M01_GettingStarted/M01_Lesson.qmd
        - lessons/M01_GettingStarted/M01_SSH.qmd
        - lessons/M01_GettingStarted/M01_Activity_GitHub.qmd
        # - lessons/M01_GettingStarted/Untitled.ipynb
    # - part: "M02 Introducing Python"
    #   chapters:
    # - part: "M03 Python Control Structures"
    #   chapters:
    # - part: "M04 Python Functions"
    #   chapters:
    # - part: "M05 Numeric Python (NumPy)"
    #   chapters:
    # - part: "M06 Python Pandas"
    #   chapters:
    # - part: "M07 Python Classes"
    #   chapters:
    # - part: "M08 Python Testing"
    #   chapters:
    # - part: "M09 Python Modules"
    #   chapters:
    # - part: "M10 R Basics"
    #   chapters:
    # - part: "M11 R Tidyverse"
    #   chapters:
    # - part: "M12 R Visualization"
    #   chapters:
    # - part: "M13 Project Management"
    #   chapters:
    # - part: "M14 Conclusion"
    #   chapters:
    - part: "Backmatter"
      chapters:
      - references.qmd

format:
  html:
    toc: true

bibliography:
  - refs.bib




